# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - tanmaycgmglucose

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_a7aedbb16c8a42b19e7748e657c6c502 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_c4ef893b451d442991407f532625de2c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_a7aedbb16c8a42b19e7748e657c6c502 }}/nightscout/cgm-remote-monitor:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'tanmaycgmglucose'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_da56288b4e7b4eb8ae49f223ae4be4c3 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_a7aedbb16c8a42b19e7748e657c6c502 }}/nightscout/cgm-remote-monitor:${{ github.sha }}'